### ISSUE TITLE
I use the colab version and try to run the example, but failed

### ISSUE THREAD

**Issue by TentacleCat** [megvii-research/CoNR#13]
Note that --use-env is set by default in torchrun.
If your script expects `--local-rank` argument to be set, please
change it to read from `os.environ['LOCAL_RANK']` instead. See 
https://pytorch.org/docs/stable/distributed.html#launch-utility for 
further instructions

  warnings.warn(
usage: train.py
       [-h]
       [--world_size WORLD_SIZE]
       [--local_rank LOCAL_RANK]
       [--dataloader_imgsize DATALOADER_IMGSIZE]
       [--batch_size BATCH_SIZE]
       [--model_name MODEL_NAME]
       [--dataloaders DATALOADERS]
       [--mode {train,test}]
       [--test_input_person_images TEST_INPUT_PERSON_IMAGES]
       [--test_input_poses_images TEST_INPUT_POSES_IMAGES]
       [--test_checkpoint_dir TEST_CHECKPOINT_DIR]
       [--test_output_dir TEST_OUTPUT_DIR]
       [--test_output_video TEST_OUTPUT_VIDEO]
       [--test_output_udp TEST_OUTPUT_UDP]
       [--test_pose_use_parser_udp TEST_POSE_USE_PARSER_UDP]
train.py: error: unrecognized arguments: --local-rank=0
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 2) local_rank: 0 (pid: 993) of binary: /usr/bin/python3
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/launch.py", line 196, in <module>
    main()
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/launch.py", line 192, in main
    launch(args)
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/launch.py", line 177, in launch
    run(args)
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/run.py", line 785, in run
    elastic_launch(
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/launcher/api.py", line 250, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
train.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-05-13_16:38:58
  host      : 38b080a41a03
  rank      : 0 (local_rank: 0)
  exitcode  : 2 (pid: 993)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================

**Comment by transpchan** [comment]
抱歉，由于部分作者只对水文章感兴趣，v1已经没人维护了。建议改用 https://github.com/transpchan/Live3D-v2 。
